apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gova-pvclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
